config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "lists#index"
  resources :lists, except: :index do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: [:list]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @movie = Movie.find(params['bookmark']['movie_id'])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def new
      # We need @restaurant in our `simple_form_for`
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  def update
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="main-image">
    <div class="index-title">
      <h1>Nouveau Film</h1>
      <p>Choisis et commente un film pour ta liste</p>
    </div>
  </div>



<div class="container mt-3">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment, label: "Ton commentaire" %>
    <%= f.association :movie, label: "Choisis ton film" %>
    <%= f.button :submit, value: "Ajouter",class: "btn btn-primary" %>
  <% end %>
  <br>
  <%= link_to "Retour", list_path(@list), class:"btn btn-light"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/index.html.erb
  <div class="main-image">
    <div class="index-title">
      <h1>Mes films</h1>
      <p>Les films à voir</p>
    </div>
  </div>

  <div class="container">
    <div class="add-button">
      <p><%= @lists.count %> listes</p>
    </div>
    <div class="cards mb-3">
      <% @lists.each do |list| %>
       <%= link_to list_path(list) do%>
          <% if list.bookmarks.first != nil %>
            <% url = ("url" + "(" + list.bookmarks.first.movie.poster_url + ")")%>
          <%else %>
            <% url = ("url(https://hips.hearstapps.com/hmg-prod/images/hbz-042517-oldhollywood-1493167401.jpg)") %>
          <%end%>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), <%=url%>">
            <h3><%= list.name %></h3>
          </div>
        <% end %>
      <% end %>
      <div class="flip-card" data-controller="click" >
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <h3>Rajouter une Liste</h3>
          </div>
          <div class="flip-card-back">
              <div class="card-form">
                <%= simple_form_for(@list) do |f| %>
                    <%= f.input :name, label: false, placeholder: "Nom de ta liste" %>
                    <%= f.button :submit, value: "Ajouter",class: "btn btn-primary" %>
                  <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/lists/new.html.erb
<div class="container">
<h1>Lists#new</h1>
  <p>Crée une nouvelle liste avec tes films dedans</p>

  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, label: false, placeholder: "coucou" %>
    <%= f.submit %>
  <% end %>
  <br>
  <%= link_to "Go Back", lists_path, class:"btn btn-light"  %>
</div>

app/views/lists/show.html.erb
<div id="show-image">
  <h1><%= @list.name %></h1>
</div>
<div class="container">
<div class="show-button">
  <%= link_to "Retour", root_path, class:"btn btn-light" %>
  <div>
    <%= link_to "+ Film", new_list_bookmark_path(@list), class:"btn btn-secondary" %>
    <%= link_to "Supprimer la liste", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger"  %>
  </div>
</div>
<div class="cards-movie">
  <% @list.bookmarks.each do |bookmark|%>
    <div class="movie-card">
    <img src="<%= bookmark.movie.poster_url %>" alt="Photo du film <%= bookmark.movie.title %>" class="img-movie">
      <div class="movie-card-text">
        <div>
          <h3><%= bookmark.movie.title %></h3>
          <p><%= bookmark.movie.overview %></p>
        </div>
        <div class="movie-card-footer">
          <div>
          <i class="fa-solid fa-quote-left mr-1"></i>
          <%= bookmark.comment %>
          </div>
          <%= link_to "Supprimer", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>
<br>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>